### ISSUE TITLE
Campfire extinguishes before respawn

### ISSUE THREAD

**Issue by TucoErthal** [The-Fireplace-Minecraft-Mods/Home-Camp#3]
Mod version: 1.0.2 for MC 1.16.4
Client Version: Fabric 0.10.6+build.214-1.16.3
Fabric API: fabric-api-0.24.3+build.414-1.16

Config
![image](https://user-images.githubusercontent.com/67657590/99178121-e1f60200-26ee-11eb-890c-c516636beff4.png)

Whenever I sneak click a lit campfire or soul campfire it correctly set my respawn point, except when I die, the campfire seems to be extinguished before I respawn, which invalidates the respawn and throws me at the world center spawnpoint.

![2020-11-15_04 05 53](https://user-images.githubusercontent.com/67657590/99178222-a60f6c80-26ef-11eb-8285-820226b06798.png)
![2020-11-15_04 06 08](https://user-images.githubusercontent.com/67657590/99178225-ac054d80-26ef-11eb-9be5-bb79d5315471.png)

**Comment by The-Fireplace** [comment]
I'm assuming this is singleplayer?

**Comment by The-Fireplace** [comment]
It seems to be working fine on my end. Do you have any other mods loaded that mess with campfires or respawning that you know of?
